POST {{host}}/api/auth/signup HTTP/1.1
content-type: application/json

{
  "user": {    
    "firstName": "John",
    "lastName": "McLane",
    "email": "any_email@mail.com",
    "password": "any_password"
  }
}

###

POST {{host}}/api/auth/signin HTTP/1.1
content-type: application/json

{
  "credential": {    
    "email": "any_email@mail.com",
    "password": "any_password"
  }
}